highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://michael.alexander.mitchell.com
author: Michael Mitchell

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl:
title: Michael Mitchell
name: Michael Mitchell
email: michael.alexander.mitchell@gmail.com
email_full: mailto:michael.alexander.mitchell@gmail.com
website: michaelalexandermitchell.com
website_full: https://michaelalexandermitchell.com
linkedin: mikeamitchell
github: mmitchell
twitter: mikealxmitchell
city: San Francisco
state: CA
google_analytics: UA-40386244-1

# needed for travis-ci build
exclude: [vendor]

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"